version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.8.34-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
    networks:
      - chat-network
    depends_on:
      - rasa-actions
  rasa-actions:
    build:
      dockerfile: ./actions/Dockerfile
    container_name: chat_rasa_actions
    ports:
      - 5055:5055
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge