version: '3.0'
services:
  rasa:
    container_name: rasa-core
    image: rasa/rasa:3.6.10-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    entrypoint:
      - rasa
      - run
      - --enable-api
    networks:
      - chat-network
  rasa-actions:
    build:
      dockerfile: ./actions/Dockerfile
    container_name: chat_rasa_actions
    ports:
      - 5055:5055
    networks:
      - chat-network
networks:
  chat-network:
    driver: bridge
